DX-2324 Overhaul Sample for New SDK
Bandwidth-Samples/messaging-send-receive-sms-ruby pull request #3
Opened 2021-12-09 16:56 UTC by ckoegel

2022-01-06 19:27 UTC, ajrice6713 requested changes

2022-01-06 19:27 UTC, ajrice6713 commented on README.md
> -LOCAL_PORT                           # The port number you wish to run the sample on
Can you revert these back to the original order?

2022-01-17 15:19 UTC, ajrice6713 submitted a review, later dismissed

2022-01-17 15:45 UTC, hamermike approved these changes, later dismissed

2022-02-17 16:25 UTC, ckoegel commented on README.md
>  You can view your public URL at `http://127.0.0.1:{LOCAL_PORT}` after ngrok is running.  You can also view the status of the tunnel and requests/responses here.
```suggestion
You can view your public URL at `http://127.0.0.1:4040` after ngrok is running.  You can also view the status of the tunnel and requests/responses here.
```

2023-10-09 14:35 UTC, brianluisgomez approved these changes

2023-10-18 18:58 UTC, merged